# Generated by Django 4.2 on 2023-05-03 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(default=None, max_length=150, verbose_name='Division Name')),
                ('division_shorthand_name', models.CharField(default=None, max_length=50, verbose_name='Shorthand Name')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(default=None, max_length=150, verbose_name='Section Name')),
                ('section_shorthand_name', models.CharField(default=None, max_length=50, verbose_name='Shorthand Name')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.division')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_id_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='ID number')),
                ('personnel_mi', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Middlename/M.I')),
                ('employee_id_number', models.IntegerField(blank=True, default=None, null=True)),
                ('employee_division', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.division')),
                ('employee_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personnel.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
