# Generated by Django 4.2 on 2023-05-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='employee_division',
            new_name='personnel_division',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='employee_section',
            new_name='personnel_section',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='employee_id_number',
        ),
    ]
