# Generated by Django 4.2 on 2023-05-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_rename_employee_division_personnel_personnel_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='signatory',
            field=models.BooleanField(default=False),
        ),
    ]
