# Generated by Django 4.2 on 2023-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_personnel_signatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='role',
            field=models.IntegerField(default=3),
        ),
    ]
