# Generated by Django 4.2 on 2023-05-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_personnel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='role',
        ),
    ]
