# Generated by Django 4.2 on 2023-09-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_remove_personnel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='personnel_position',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Position/Designation'),
        ),
    ]
