# Generated by Django 4.2 on 2023-10-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_personnel_personnel_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='personnel_station',
            field=models.CharField(blank=True, default='MGB-X Regional Office', max_length=150, verbose_name='Official Station'),
        ),
    ]
