# Generated by Django 4.2 on 2023-10-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_personnel_personnel_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='personnel_suffix',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Suffix'),
        ),
    ]
