# Generated by Django 4.2 on 2023-10-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_personnel_personnel_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='personnel_designation',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Designation'),
        ),
    ]
