# Generated by Django 4.2 on 2023-10-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_personnel_personnel_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='personnel_designation',
            field=models.CharField(blank=True, choices=[('', '------------------'), ('RD', 'Regional Director'), ('DC', 'Division Chief'), ('SC', 'Section Chief')], default=None, max_length=100, null=True, verbose_name='Designation'),
        ),
    ]
