# Generated by Django 4.2 on 2023-10-02 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import to.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TO',
            fields=[
                ('to_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(default=None, max_length=100, verbose_name='TO Number')),
                ('to_date', models.DateField(verbose_name='TO Date')),
                ('to_departure', models.DateField(verbose_name='Departure Date')),
                ('to_arrival', models.DateField(verbose_name='Arrival Date')),
                ('to_destination', models.TextField(default=None, null='False', verbose_name='Destination')),
                ('to_purpose', models.TextField(default=None, null='False', verbose_name='Purpose')),
                ('to_scan_copy', models.FileField(default=None, upload_to=to.models.to_upload_path, verbose_name='Scanned Copy')),
            ],
            options={
                'verbose_name_plural': 'TO',
            },
        ),
        migrations.CreateModel(
            name='to_assigned_personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personnel')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to.to', verbose_name='TO')),
            ],
            options={
                'verbose_name_plural': 'Assigned Personnel - TO',
            },
        ),
    ]
