# Generated by Django 4.2 on 2023-10-02 04:15

from django.db import migrations, models
import to.models


class Migration(migrations.Migration):

    dependencies = [
        ('to', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to',
            name='to_scan_copy',
            field=models.FileField(default=None, null=True, upload_to=to.models.to_upload_path, verbose_name='Scanned Copy'),
        ),
    ]
