# Generated by Django 4.2 on 2023-10-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to', '0002_alter_to_to_scan_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='to',
            old_name='to_id',
            new_name='id',
        ),
    ]
