# Generated by Django 4.2 on 2023-05-03 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSO',
            fields=[
                ('rso_number', models.CharField(default=None, max_length=100, primary_key=True, serialize=False, verbose_name='RSO Number')),
                ('rso_date', models.DateField(verbose_name='RSO Date')),
                ('rso_subject', models.TextField(default=None, verbose_name='Subject')),
                ('rso_scheduled_dates_from', models.DateField(default=None, verbose_name='From')),
                ('rso_scheduled_dates_to', models.DateField(default=None, verbose_name='To')),
                ('rso_remarks', models.TextField(default=None, verbose_name='Remarks')),
                ('rso_scan_copy', models.FileField(default=None, upload_to='', verbose_name='Scanned Copy')),
                ('rso_signatory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Signatory')),
            ],
        ),
        migrations.CreateModel(
            name='rso_assinged_personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personnel')),
                ('rso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rso.rso', verbose_name='RSO')),
            ],
        ),
    ]
