# Generated by Django 4.2 on 2023-05-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rso',
            options={'verbose_name_plural': 'RSO'},
        ),
        migrations.AlterModelOptions(
            name='rso_assinged_personnel',
            options={'verbose_name_plural': 'Assigned Personnel'},
        ),
        migrations.AlterField(
            model_name='rso',
            name='rso_remarks',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Remarks'),
        ),
    ]
