# Generated by Django 4.2 on 2023-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0002_alter_rso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rso',
            name='rso_scan_copy',
            field=models.FileField(default=None, upload_to='media/', verbose_name='Scanned Copy'),
        ),
    ]
