# Generated by Django 4.2 on 2023-05-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0003_alter_rso_rso_scan_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rso',
            name='rso_scan_copy',
            field=models.FileField(default=None, upload_to='rso_upload_path', verbose_name='Scanned Copy'),
        ),
    ]
