# Generated by Django 4.2 on 2023-09-19 06:03

from django.db import migrations, models
import rso.models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0004_alter_rso_rso_scan_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rso',
            name='rso_scan_copy',
            field=models.FileField(default=None, upload_to=rso.models.rso_upload_path, verbose_name='Scanned Copy'),
        ),
    ]
