# Generated by Django 4.2 on 2023-09-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0005_alter_rso_rso_scan_copy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rso_assinged_personnel',
            options={'verbose_name_plural': 'Assigned Personnel - RSO'},
        ),
    ]
