# Generated by Django 4.2 on 2024-02-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rso', '0006_alter_rso_assinged_personnel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rso',
            name='rso_scheduled_dates_from',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='rso',
            name='rso_scheduled_dates_to',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='To'),
        ),
    ]
